version: '3.8'

services:
  restaurant_menu_app:
    container_name: restaurant_menu_app
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "
        alembic upgrade head &&
        SQLALCHEMY_SILENCE_UBER_WARNING=1 pytest -vv
      "
    networks:
      - test_network
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_db:
        condition: service_healthy
  
  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    volumes:
      - test-db-data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - test_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_db:
      container_name: redis_db
      image: redis:latest
      expose:
        - 6379
      ports:
        - "6379:6379"
      networks:
        - test_network
      healthcheck:
        test: ["CMD-SHELL", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
  
networks:
    test_network:
        name: test_network

volumes:
  test-db-data: