"""Creating tables

Revision ID: 25296b660769
Revises: 
Create Date: 2023-01-16 19:10:19.096290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25296b660769'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
