name: project CI

on: push

jobs:
  create-envfile:

    runs-on: ubuntu-latest

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_TEST_DB_NAME: test
        envkey_DB_USER: test
        envkey_DB_PASS: test
        envkey_DB_HOST: postgres
        envkey_DB_PORT: 5432
        envkey_REDIS_HOST: redis
        envkey_REDIS_PORT: 6379
        envkey_REDIS_DB: 1
        envkey_REDIS_EXP: 100
        file_name: .env
        directory: restaurant_menu_FastAPI
        fail_on_empty: false

  container-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: pipx install poetry==1.2.2
    - run: make install
    - run: make migration
    - run: make hooks
    - name: test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
